name: CI Pipeline

on:
  push:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'composer.json'
      - '.github/workflows/**'
      - 'Makefile'
      - 'makefile'
      - 'phpcs.xml'
      - 'phpstan.neon'
      - '.env'
  pull_request:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'composer.json'
      - '.github/workflows/**'
      - 'Makefile'
      - 'makefile'
      - 'phpcs.xml'
      - 'phpstan.neon'
      - '.env'
  workflow_dispatch:

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_CONFIG: /tmp/.docker
        run: |
          mkdir -p $DOCKER_CONFIG
          echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USER_NAME }}" --password-stdin

      - name: Install dependencies
        run: make install

      - name: Check Code Standards
        run: make phpcs

      - name: Cleanup
        if: always()
        run: make remove

      - name: Logout from Docker Hub
        if: always()
        env:
          DOCKER_CONFIG: /tmp/.docker
        run: docker logout

  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_CONFIG: /tmp/.docker
        run: |
          mkdir -p $DOCKER_CONFIG
          echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USER_NAME }}" --password-stdin

      - name: Install dependencies
        run: make install

      - name: Run PHPStan
        run: make phpstan

      - name: Cleanup
        if: always()
        run: make remove

      - name: Logout from Docker Hub
        if: always()
        env:
          DOCKER_CONFIG: /tmp/.docker
        run: docker logout
